// Code generated by repogen. DO NOT EDIT.
package repository

import (
	"database/sql"
	"time"
)

var (
	_ = time.UTC
)

const Tweet_CreateTableStm = `CREATE TABLE "tweet" (
	id INTEGER NOT NULL PRIMARY KEY,
	user_id INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL,
	language STRING,
	longitude FLOAT,
	latitude FLOAT
)`
const Tweet_CreateIndexStm_user = "CREATE INDEX user ON tweet(user_id)"
const Tweet_InsertStm = `
INSERT INTO tweet (
	id,
	user_id,
	created_at,
	language,
	longitude,
	latitude
) VALUES (
	?,
	?,
	?,
	?,
	?,
	?
)
`

func (r *Tweet) MarshalRow() []interface{} {
	return []interface{}{
		r.ID,
		r.UserID,
		r.CreatedAt,
		r.Language,
		r.Longitude,
		r.Latitude,
	}
}
func (r *Tweet) UnmarshalRow(row interface{ Scan(...interface{}) error }) error {
	return row.Scan(
		&r.ID,
		&r.UserID,
		&r.CreatedAt,
		&r.Language,
		&r.Longitude,
		&r.Latitude,
	)
}

type TweetRepo struct {
	DB *sql.DB
}

func (r *TweetRepo) CreateTable() error {
	if _, err := r.DB.Exec(Tweet_CreateTableStm); err != nil {
		return err
	}
	if _, err := r.DB.Exec(Tweet_CreateIndexStm_user); err != nil {
		return err
	}
	return nil
}
func (r *TweetRepo) InsertMany(rs []*Tweet) error {
	tx, err := r.DB.Begin()
	if err != nil {
		return err
	}
	stm, err := tx.Prepare(Tweet_InsertStm)
	if err != nil {
		return err
	}
	defer stm.Close()
	for _, r := range rs {
		if _, err := stm.Exec(r.MarshalRow()...); err != nil {
			return err
		}
	}
	if err := tx.Commit(); err != nil {
		return err
	}
	return nil
}
func (r *TweetRepo) Get(id int) (*Tweet, error) {
	row := r.DB.QueryRow("SELECT * FROM tweet WHERE id = ?", id)
	var res Tweet
	if err := res.UnmarshalRow(row); err != nil {
		return nil, err
	}
	return &res, nil
}
func (r *TweetRepo) List(where string, args ...interface{}) ([]*Tweet, error) {
	q := "SELECT * FROM tweet"
	if where != "" {
		q += " WHERE " + where
	}
	rows, err := r.DB.Query(q, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var ress []*Tweet
	for rows.Next() {
		var res Tweet
		if err := res.UnmarshalRow(rows); err != nil {
			return nil, err
		}
		ress = append(ress, &res)
	}
	return ress, nil
}
func (r *TweetRepo) ListUser(user_id int) ([]*Tweet, error) {
	rows, err := r.DB.Query("SELECT * FROM tweet WHERE user_id=?", user_id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var ress []*Tweet
	for rows.Next() {
		var res Tweet
		if err := res.UnmarshalRow(rows); err != nil {
			return nil, err
		}
		ress = append(ress, &res)
	}
	return ress, nil
}
